import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1745417394813 implements MigrationInterface {
    name = 'Default1745417394813'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "subjects" ("id" SERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" SERIAL NOT NULL, "name" text NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Videos" ("id" SERIAL NOT NULL, "title" text NOT NULL, "url" text NOT NULL, "description" text NOT NULL, "room_id" integer, CONSTRAINT "PK_3cafd1e310bdf514e0d6a94df1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coach" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "apelido" text, "cpf" character varying(11), "dataNascimento" TIMESTAMP NOT NULL, "foto" text, "email" text, "telefone" text, CONSTRAINT "PK_c2ca0875fe0755b197d0147713d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipe_tecnico" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "equipeId" uuid NOT NULL, "coachId" uuid NOT NULL, "data_contratacao" TIMESTAMP, "data_desligamento" TIMESTAMP, CONSTRAINT "PK_3645c4662eb8dceebcd30ec5dba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipe_partida" ("partidaId" uuid NOT NULL, "casaId" uuid NOT NULL, "visitanteId" uuid NOT NULL, CONSTRAINT "PK_00a8e15402597f8c7f7cb5de8e8" PRIMARY KEY ("partidaId", "casaId", "visitanteId"))`);
        await queryRunner.query(`CREATE TABLE "falta" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "tipo" "public"."falta_tipo_enum" NOT NULL, "tempo" TIME NOT NULL, "local" integer NOT NULL, "jogadorAutorId" uuid, "jogadorSofreuId" uuid, "partidaId" uuid, "arbitroId" uuid, "equipeId" uuid, CONSTRAINT "PK_cf7ea333a7fac042128cb9c9cf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arbitro" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "apelido" text, "cpf" character varying(11), "dataNascimento" TIMESTAMP NOT NULL, "foto" text, "email" text, "telefone" text, CONSTRAINT "PK_267b7657c367d1e07cb6f95c700" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quadra" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "comprimento" numeric(6,2) NOT NULL, "largura" numeric(6,2) NOT NULL, "endereco" text, "telefone" text, "piso" "public"."quadra_piso_enum" NOT NULL, "responsavel" text, CONSTRAINT "PK_488dbc852c932ae37243f43727c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finalizacao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "defesa" boolean NOT NULL, "bloqueio" boolean NOT NULL, "falta" boolean NOT NULL, "gol" boolean NOT NULL, "seteMetros" boolean NOT NULL, "penalti" boolean NOT NULL, "pe" "public"."finalizacao_pe_enum" NOT NULL, "periodo" integer NOT NULL, "posicaoCampo" json, "posicaoGol" json, "tempo" TIME NOT NULL, "jogadorAtacanteId" uuid, "jogadorDefensorId" uuid, "partidaId" uuid, "equipeId" uuid, CONSTRAINT "PK_1966b95e064971893222950134f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drible" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "sucesso" boolean NOT NULL, "desarme" boolean NOT NULL, "local" integer NOT NULL, "pe" "public"."drible_pe_enum" NOT NULL, "tempo" TIME NOT NULL, "jogadorAtacanteId" uuid, "jogadorDefensorId" uuid, "partidaId" uuid, "equipeId" uuid, CONSTRAINT "PK_f1a942657d5fef8f5d2fe79c3c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "desarme" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "sucesso" boolean NOT NULL, "pe" "public"."desarme_pe_enum" NOT NULL, "local" integer NOT NULL, "tempo" TIME NOT NULL, "jogadorDesarmeId" uuid, "jogadorDesarmadoId" uuid, "partidaId" uuid, "equipeId" uuid, CONSTRAINT "PK_53cdd42691a5bb6c69428e85d5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cartao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "tipo" "public"."cartao_tipo_enum" NOT NULL, "tempo" TIME NOT NULL, "local" integer NOT NULL, "descricao" character varying, "jogadorId" uuid, "partidaId" uuid, "arbitroId" uuid, "equipeId" uuid, CONSTRAINT "PK_4e39f2f0b54a26014e575465719" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "partida" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "publicoPresente" integer, "status" "public"."partida_status_enum" NOT NULL DEFAULT '0', "data" TIMESTAMP, "rodada" integer, "quadraId" uuid, "torneioId" uuid, CONSTRAINT "PK_10d41cde1840f4c9d8c44d245af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gol" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "tempoGol" TIME NOT NULL, "golContra" boolean NOT NULL, "periodo" integer NOT NULL, "posicaoCampo" json, "posicaoGol" json, "assistenteId" uuid, "jogadorDefensorId" uuid, "jogadorId" uuid, "partidaId" uuid, "equipeId" uuid, "finalizacaoId" uuid, CONSTRAINT "REL_de65a25b0875662849e2afeb8d" UNIQUE ("finalizacaoId"), CONSTRAINT "PK_534558f06933029db7f41901c9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jogador" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "peDominante" smallint NOT NULL DEFAULT '1', "apelido" text, "dataNascimento" TIMESTAMP NOT NULL, "posicao" smallint NOT NULL DEFAULT '4', "foto" text, "altura" numeric(3,2) NOT NULL, "cpf" character varying(11), "telefone" text, "cidadeNatal" text, CONSTRAINT "PK_022ee9467b7f3fd077eb6fb8969" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipe_jogador" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jogadorId" uuid NOT NULL, "equipeId" uuid NOT NULL, "data_contratacao" TIMESTAMP, "data_desligamento" TIMESTAMP, "dorsal" integer, "capitao" boolean, CONSTRAINT "PK_f62797483dd3799d49b0b8c9404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipe" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "telefone" text, "endereco" text, "logo" text NOT NULL, CONSTRAINT "PK_f2503347d661dac29b5a0035f22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "torneio" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP, "updateAt" TIMESTAMP, "isDeleted" boolean NOT NULL, "name" text NOT NULL, "status" "public"."torneio_status_enum" NOT NULL DEFAULT '0', "tipo" "public"."torneio_tipo_enum" NOT NULL DEFAULT '1', "foto" text, "edicao" text NOT NULL, CONSTRAINT "PK_d1a66905ea4b4fb7a2a1c19c6a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_subject" ("room_id" integer NOT NULL, "subject_id" integer NOT NULL, CONSTRAINT "PK_6b3738a7b93c77fd6d9333b638a" PRIMARY KEY ("room_id", "subject_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f227421d2ef64ab086261ac07f" ON "room_subject" ("room_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a05f10c497f5f7db3022664a6d" ON "room_subject" ("subject_id") `);
        await queryRunner.query(`CREATE TABLE "partida_arbitro" ("partidaId" uuid NOT NULL, "arbitroId" uuid NOT NULL, CONSTRAINT "PK_eb54b4109b4b7190bdd9a1c7d0c" PRIMARY KEY ("partidaId", "arbitroId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bedb627989ddeccb67315765b" ON "partida_arbitro" ("partidaId") `);
        await queryRunner.query(`CREATE INDEX "IDX_95a2b0f7f25c04f36e4105bfed" ON "partida_arbitro" ("arbitroId") `);
        await queryRunner.query(`CREATE TABLE "equipe_torneio" ("torneioId" uuid NOT NULL, "equipeId" uuid NOT NULL, CONSTRAINT "PK_23b1adb3613a6ac9ab62ec9187b" PRIMARY KEY ("torneioId", "equipeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe1aeb8c646a795d8cbffde0a2" ON "equipe_torneio" ("torneioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_905e0de7388931728198fc0ba0" ON "equipe_torneio" ("equipeId") `);
        await queryRunner.query(`ALTER TABLE "Videos" ADD CONSTRAINT "FK_2e75e3fc0f660900b12d705a253" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_tecnico" ADD CONSTRAINT "FK_f9e541af719a4964989b5db8e38" FOREIGN KEY ("coachId") REFERENCES "coach"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_tecnico" ADD CONSTRAINT "FK_e29ad79f9c5d7ed7320c8bb60d0" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" ADD CONSTRAINT "FK_c340f612bc05ee5ed2d314e40e3" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" ADD CONSTRAINT "FK_2c1e08d56dc1ee148271b8218bf" FOREIGN KEY ("casaId") REFERENCES "equipe"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" ADD CONSTRAINT "FK_28611fd70be8be5ec6c1a4cbb37" FOREIGN KEY ("visitanteId") REFERENCES "equipe"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "falta" ADD CONSTRAINT "FK_417964689a57efbc395643dadce" FOREIGN KEY ("jogadorAutorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "falta" ADD CONSTRAINT "FK_73c4d7ab09d5623d143c945e339" FOREIGN KEY ("jogadorSofreuId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "falta" ADD CONSTRAINT "FK_131678518f2af9abb37292e39a9" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "falta" ADD CONSTRAINT "FK_41e1e7e1f3d0592b9e7ca9671f5" FOREIGN KEY ("arbitroId") REFERENCES "arbitro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "falta" ADD CONSTRAINT "FK_b33687c9c23d42a84ffb723f5c1" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalizacao" ADD CONSTRAINT "FK_995af74dc6d9628447d609b6856" FOREIGN KEY ("jogadorAtacanteId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalizacao" ADD CONSTRAINT "FK_44b35f38359c595ec8bd77e3320" FOREIGN KEY ("jogadorDefensorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalizacao" ADD CONSTRAINT "FK_c59c246d3b962f56e0382cc773b" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalizacao" ADD CONSTRAINT "FK_876b21e886d72097f9d65248e32" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drible" ADD CONSTRAINT "FK_b6970e0174ee364397cd1635db8" FOREIGN KEY ("jogadorAtacanteId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drible" ADD CONSTRAINT "FK_dfa71af16ca74dec21f726c4abd" FOREIGN KEY ("jogadorDefensorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drible" ADD CONSTRAINT "FK_26741a88d3e54c55780a71b03c4" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drible" ADD CONSTRAINT "FK_9ff028a977993304d688d16550c" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "desarme" ADD CONSTRAINT "FK_febc8c621c4e8b79dbe5d79cbe9" FOREIGN KEY ("jogadorDesarmeId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "desarme" ADD CONSTRAINT "FK_c514482c69ec464d9f814d62b64" FOREIGN KEY ("jogadorDesarmadoId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "desarme" ADD CONSTRAINT "FK_b2f277daf2f670814e39575ff05" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "desarme" ADD CONSTRAINT "FK_fbdf2808583532e121c58b5e91d" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartao" ADD CONSTRAINT "FK_72c0cf3f1ef679e0d96530b3747" FOREIGN KEY ("jogadorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartao" ADD CONSTRAINT "FK_89a2c53d696c550f89c58e278f3" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartao" ADD CONSTRAINT "FK_ce5aad07f73e9c1bbe16cf9456b" FOREIGN KEY ("arbitroId") REFERENCES "arbitro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartao" ADD CONSTRAINT "FK_952702b2d01e6407994d10ba8e9" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partida" ADD CONSTRAINT "FK_e5fbf8ebb4af3674e9a227554d7" FOREIGN KEY ("quadraId") REFERENCES "quadra"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partida" ADD CONSTRAINT "FK_3a4b1d7566461d2f962fc7351e1" FOREIGN KEY ("torneioId") REFERENCES "torneio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_84abf39a193a154cf0d0ea37ef0" FOREIGN KEY ("assistenteId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_c1f88dc7b5af91cb5213faaad33" FOREIGN KEY ("jogadorDefensorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_e633dc1ea28553dde0de9099056" FOREIGN KEY ("jogadorId") REFERENCES "jogador"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_a3d28672293c1d42bea757b6c8a" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_4483ead6789a853299f9e554396" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gol" ADD CONSTRAINT "FK_de65a25b0875662849e2afeb8dc" FOREIGN KEY ("finalizacaoId") REFERENCES "finalizacao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_jogador" ADD CONSTRAINT "FK_afba77351bbe5788f9f8e29f338" FOREIGN KEY ("jogadorId") REFERENCES "jogador"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_jogador" ADD CONSTRAINT "FK_0eb030a8aa2b6c87439e0779011" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_subject" ADD CONSTRAINT "FK_f227421d2ef64ab086261ac07fd" FOREIGN KEY ("room_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_subject" ADD CONSTRAINT "FK_a05f10c497f5f7db3022664a6d6" FOREIGN KEY ("subject_id") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partida_arbitro" ADD CONSTRAINT "FK_6bedb627989ddeccb67315765b2" FOREIGN KEY ("partidaId") REFERENCES "partida"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "partida_arbitro" ADD CONSTRAINT "FK_95a2b0f7f25c04f36e4105bfed5" FOREIGN KEY ("arbitroId") REFERENCES "arbitro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipe_torneio" ADD CONSTRAINT "FK_fe1aeb8c646a795d8cbffde0a27" FOREIGN KEY ("torneioId") REFERENCES "torneio"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "equipe_torneio" ADD CONSTRAINT "FK_905e0de7388931728198fc0ba08" FOREIGN KEY ("equipeId") REFERENCES "equipe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "equipe_torneio" DROP CONSTRAINT "FK_905e0de7388931728198fc0ba08"`);
        await queryRunner.query(`ALTER TABLE "equipe_torneio" DROP CONSTRAINT "FK_fe1aeb8c646a795d8cbffde0a27"`);
        await queryRunner.query(`ALTER TABLE "partida_arbitro" DROP CONSTRAINT "FK_95a2b0f7f25c04f36e4105bfed5"`);
        await queryRunner.query(`ALTER TABLE "partida_arbitro" DROP CONSTRAINT "FK_6bedb627989ddeccb67315765b2"`);
        await queryRunner.query(`ALTER TABLE "room_subject" DROP CONSTRAINT "FK_a05f10c497f5f7db3022664a6d6"`);
        await queryRunner.query(`ALTER TABLE "room_subject" DROP CONSTRAINT "FK_f227421d2ef64ab086261ac07fd"`);
        await queryRunner.query(`ALTER TABLE "equipe_jogador" DROP CONSTRAINT "FK_0eb030a8aa2b6c87439e0779011"`);
        await queryRunner.query(`ALTER TABLE "equipe_jogador" DROP CONSTRAINT "FK_afba77351bbe5788f9f8e29f338"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_de65a25b0875662849e2afeb8dc"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_4483ead6789a853299f9e554396"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_a3d28672293c1d42bea757b6c8a"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_e633dc1ea28553dde0de9099056"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_c1f88dc7b5af91cb5213faaad33"`);
        await queryRunner.query(`ALTER TABLE "gol" DROP CONSTRAINT "FK_84abf39a193a154cf0d0ea37ef0"`);
        await queryRunner.query(`ALTER TABLE "partida" DROP CONSTRAINT "FK_3a4b1d7566461d2f962fc7351e1"`);
        await queryRunner.query(`ALTER TABLE "partida" DROP CONSTRAINT "FK_e5fbf8ebb4af3674e9a227554d7"`);
        await queryRunner.query(`ALTER TABLE "cartao" DROP CONSTRAINT "FK_952702b2d01e6407994d10ba8e9"`);
        await queryRunner.query(`ALTER TABLE "cartao" DROP CONSTRAINT "FK_ce5aad07f73e9c1bbe16cf9456b"`);
        await queryRunner.query(`ALTER TABLE "cartao" DROP CONSTRAINT "FK_89a2c53d696c550f89c58e278f3"`);
        await queryRunner.query(`ALTER TABLE "cartao" DROP CONSTRAINT "FK_72c0cf3f1ef679e0d96530b3747"`);
        await queryRunner.query(`ALTER TABLE "desarme" DROP CONSTRAINT "FK_fbdf2808583532e121c58b5e91d"`);
        await queryRunner.query(`ALTER TABLE "desarme" DROP CONSTRAINT "FK_b2f277daf2f670814e39575ff05"`);
        await queryRunner.query(`ALTER TABLE "desarme" DROP CONSTRAINT "FK_c514482c69ec464d9f814d62b64"`);
        await queryRunner.query(`ALTER TABLE "desarme" DROP CONSTRAINT "FK_febc8c621c4e8b79dbe5d79cbe9"`);
        await queryRunner.query(`ALTER TABLE "drible" DROP CONSTRAINT "FK_9ff028a977993304d688d16550c"`);
        await queryRunner.query(`ALTER TABLE "drible" DROP CONSTRAINT "FK_26741a88d3e54c55780a71b03c4"`);
        await queryRunner.query(`ALTER TABLE "drible" DROP CONSTRAINT "FK_dfa71af16ca74dec21f726c4abd"`);
        await queryRunner.query(`ALTER TABLE "drible" DROP CONSTRAINT "FK_b6970e0174ee364397cd1635db8"`);
        await queryRunner.query(`ALTER TABLE "finalizacao" DROP CONSTRAINT "FK_876b21e886d72097f9d65248e32"`);
        await queryRunner.query(`ALTER TABLE "finalizacao" DROP CONSTRAINT "FK_c59c246d3b962f56e0382cc773b"`);
        await queryRunner.query(`ALTER TABLE "finalizacao" DROP CONSTRAINT "FK_44b35f38359c595ec8bd77e3320"`);
        await queryRunner.query(`ALTER TABLE "finalizacao" DROP CONSTRAINT "FK_995af74dc6d9628447d609b6856"`);
        await queryRunner.query(`ALTER TABLE "falta" DROP CONSTRAINT "FK_b33687c9c23d42a84ffb723f5c1"`);
        await queryRunner.query(`ALTER TABLE "falta" DROP CONSTRAINT "FK_41e1e7e1f3d0592b9e7ca9671f5"`);
        await queryRunner.query(`ALTER TABLE "falta" DROP CONSTRAINT "FK_131678518f2af9abb37292e39a9"`);
        await queryRunner.query(`ALTER TABLE "falta" DROP CONSTRAINT "FK_73c4d7ab09d5623d143c945e339"`);
        await queryRunner.query(`ALTER TABLE "falta" DROP CONSTRAINT "FK_417964689a57efbc395643dadce"`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" DROP CONSTRAINT "FK_28611fd70be8be5ec6c1a4cbb37"`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" DROP CONSTRAINT "FK_2c1e08d56dc1ee148271b8218bf"`);
        await queryRunner.query(`ALTER TABLE "equipe_partida" DROP CONSTRAINT "FK_c340f612bc05ee5ed2d314e40e3"`);
        await queryRunner.query(`ALTER TABLE "equipe_tecnico" DROP CONSTRAINT "FK_e29ad79f9c5d7ed7320c8bb60d0"`);
        await queryRunner.query(`ALTER TABLE "equipe_tecnico" DROP CONSTRAINT "FK_f9e541af719a4964989b5db8e38"`);
        await queryRunner.query(`ALTER TABLE "Videos" DROP CONSTRAINT "FK_2e75e3fc0f660900b12d705a253"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_905e0de7388931728198fc0ba0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe1aeb8c646a795d8cbffde0a2"`);
        await queryRunner.query(`DROP TABLE "equipe_torneio"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95a2b0f7f25c04f36e4105bfed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bedb627989ddeccb67315765b"`);
        await queryRunner.query(`DROP TABLE "partida_arbitro"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a05f10c497f5f7db3022664a6d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f227421d2ef64ab086261ac07f"`);
        await queryRunner.query(`DROP TABLE "room_subject"`);
        await queryRunner.query(`DROP TABLE "torneio"`);
        await queryRunner.query(`DROP TABLE "equipe"`);
        await queryRunner.query(`DROP TABLE "equipe_jogador"`);
        await queryRunner.query(`DROP TABLE "jogador"`);
        await queryRunner.query(`DROP TABLE "gol"`);
        await queryRunner.query(`DROP TABLE "partida"`);
        await queryRunner.query(`DROP TABLE "cartao"`);
        await queryRunner.query(`DROP TABLE "desarme"`);
        await queryRunner.query(`DROP TABLE "drible"`);
        await queryRunner.query(`DROP TABLE "finalizacao"`);
        await queryRunner.query(`DROP TABLE "quadra"`);
        await queryRunner.query(`DROP TABLE "arbitro"`);
        await queryRunner.query(`DROP TABLE "falta"`);
        await queryRunner.query(`DROP TABLE "equipe_partida"`);
        await queryRunner.query(`DROP TABLE "equipe_tecnico"`);
        await queryRunner.query(`DROP TABLE "coach"`);
        await queryRunner.query(`DROP TABLE "Videos"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
    }

}
